packages:
  - '.'
  - 'tools/visual-regression'
allowBuilds:
  '@swc/core': true
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@playwright/test@1.63.0'
  - playwright-core@1.63.0
  - playwright@1.63.0
onlyBuiltDependencies:
  - "@swc/core"
  - "esbuild"
  - "playwright"
  - "archiver"

overrides:
  '@swc/core': 1.15.47
  '@swc/wasm': 1.15.47
