packages:
  - '.'
  - 'tools/visual-regression'
allowBuilds:
  '@swc/core': set this to true or false
  esbuild: set this to true or false
  simple-git-hooks: set this to true or false
minimumReleaseAgeExclude:
  - '@playwright/test@1.63.0'
  - playwright-core@1.63.0
  - playwright@1.63.0
onlyBuiltDependencies:
  - "@swc/core"
  - "esbuild"
  - "playwright"
  - "archiver"
